news/urls.py
from django.urls import path
from news import views

app_name = "news"

urlpatterns = [
	path('', views.news_home, name='news_list'),
    path('<int:id>/', views.news_detail, name='news_detail'),
]

owen_agriculture/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
	path('', views.home, name='home'),
    path('products/', include('products.urls')),
    path('projects/', include('projects.urls')),
    path('news/', include('news.urls')),
    path('contacts/', views.contacts, name='contacts'),
    path('about/', views.about, name='about'),
    path('owen_admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

products/urls.py
from django.urls import path
from products import views

app_name = "products"

urlpatterns = [
	path('poultry/', views.poultry_catalog, name='poultry_catalog'),
    path('pigsty/', views.pigsty_catalog, name='pigsty_catalog'),
    path('catalog/', views.full_catalog, name='full_catalog'),
    path('product/<int:id>', views.product_detail, name='product_detail'),
]

projects/urls.py
from django.urls import path
from projects import views

app_name = "projects"

urlpatterns = [
	path('', views.projects_list, name='projects_list'),
    path('<int:id>/', views.project_detail, name='project_detail'),
]

banners/models.py
from django.db import models

# Create your models here.
class Banner (models.Model):
	name = models.CharField(verbose_name='Название', max_length=100, blank=False)
	banner_image = models.ImageField(verbose_name='Картинка баннера', upload_to='banners', blank=False)
	order = models.PositiveSmallIntegerField(verbose_name='Порядок отображения', default=0)
	display = models.BooleanField(verbose_name='Показывать', default=True)

	def __str__ (self):
		return self.name

	class Meta():
		verbose_name = "Баннер"
		verbose_name_plural = "Баннеры"

owen_agriculture/views.py
from django.shortcuts import render
from django.shortcuts import get_list_or_404
from django.http import Http404
from news.models import Article
from projects.models import ProjectArticle
from banners.models import Banner

def home(request):
	try:
		latest_news = Article.objects.filter(display=True).order_by('-pub_date')[:5]
	except:
		latest_news = []

	try:
		latest_projects = ProjectArticle.objects.filter(display=True).order_by('-id')[:5]
	except:
		latest_projects = []

	try:
		banners = Banner.objects.filter(display=True).order_by('order')
	except:
		banners = []	

	context = {'latest_news':latest_news, 'latest_projects':latest_projects, 'banners':banners}
	return render(request, 'owen_agriculture/home.html', context)

def about(request):
	return render(request, 'owen_agriculture/about_company.html')

def contacts(request):
	return render(request, 'owen_agriculture/contacts.html')

def projects(request):
	return render(request, 'owen_agriculture/projects.html')

def news(request):
	return render(request, 'owen_agriculture/news.html')

owen_agriculture/templates/banner.html
{% load static %}

<div class="w3-content base-content-width">
  <div id="demo" class="carousel slide" data-ride="carousel">

    <!-- Indicators -->
    <ul class="carousel-indicators">
      <li data-target="#demo" data-slide-to="0" class="active"></li>
      <li data-target="#demo" data-slide-to="1"></li>
      <li data-target="#demo" data-slide-to="2"></li>
    </ul>
    
    <!-- The slideshow -->
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="{% static 'img/banner1.jpg' %}" alt="banner" style="width:100%;">
      </div>
      <div class="carousel-item">
        <img src="{% static 'img/banner2.jpg' %}" alt="banner" style="width:100%;">
      </div>
      <div class="carousel-item">
        <img src="{% static 'img/banner3.jpg' %}" alt="banner" style="width:100%;">
      </div>
    </div>
    
    <!-- Left and right controls -->
    <a class="carousel-control-prev" href="#demo" data-slide="prev">
      <span class="carousel-control-prev-icon"></span>
    </a>
    <a class="carousel-control-next" href="#demo" data-slide="next">
      <span class="carousel-control-next-icon"></span>
    </a>
  </div>
</div>

owen_agriculture/templates/base.html
{% load static %}
{% load django_bootstrap_breadcrumbs %}

{% block breadcrumbs %}
    {% clear_breadcrumbs %}
{% endblock %}

<!DOCTYPE html>
<html lang="ru-RU">

<head>
	<title>{% block title %} Owen Agriculture {% endblock %}</title>
	<link rel="shortcut icon" type="image/png" href="{% static 'img/owen.ico' %}" />
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
  	<meta property="og:image" content="{% static 'img/og_image.jpg' %}" />
  	<meta property="og:title" content="ОВЕН Животноводство">
  	<meta property="og:description" content="Системы микроклимата для животноводства">

	<!-- fonts -->
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Jost">
	<link href="https://fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,500,500i,700,700i&amp;amp;subset=cyrillic,cyrillic-ext,latin-ext" rel="stylesheet">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<script src='https://kit.fontawesome.com/a076d05399.js'></script>

	<!-- jQuery -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

	<!-- W3.CSS style    https://www.w3schools.com/w3css/4/w3.css     https://www.w3schools.com/w3css  -->
	<link rel="stylesheet" href="{% static 'vendors/w3.css' %}">

	<!-- Bootstrap  -->
  	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

	<!-- my style -->
	<link rel="stylesheet" href="{% static 'css/base_style.css' %}">
	<link rel="stylesheet" href="{% static 'css/breadcrumbs.css' %}">
	<link rel="stylesheet" href="{% static 'css/text-editor-extending-style.css' %}">
	<link rel="stylesheet" href="{% static 'css/main-icons.css' %}">
	<!-- my fonts -->
	<link rel="stylesheet" href="{% static 'css/topic-icons.css' %}">

</head>

<body class="text-dark text-font bg-grey" {% block scrollable %}{% endblock %}>
	<!-- Navbar -->
	<div class="d-none d-md-inline-block">{% include "navbar.html" %}</div>
	<div class="d-md-none">{% include "navbar_small_scrin.html" %}</div>

	<!-- Content -->
	<div class="w3-content base-content-width base-content-height">  
		{% block content %}{% endblock %} 
	</div>

	{% include "footer.html" %}

	{% block sidebar_scripts %} {% endblock %}
</body>
</html>

owen_agriculture/templates/breadcrumbs.html
<div class="breadcrumbs-containe">
	<div class="w-100">  
	
		<ul class="breadcrumb">
		    {% for url, label in breadcrumbs %}
		        <li>
		            {% ifnotequal forloop.counter breadcrumbs_total %}
		                <a href="{{ url }}">{{ label|safe }}</a>
		            {% else %}
		                {{ label|safe }}
		            {% endifnotequal %}
		            {% if not forloop.last %}
		                <span class="divider">/</span>
		            {% endif %}
		        </li>
		    {% endfor %}
		</ul>

	</div>
</div>

owen_agriculture/templates/footer.html
{% load static %}

<footer class='bg-granite' id="mainFooter">
<div class="w3-content base-content-width">
<div class='row p-3 m-0' >
	<div class="col-lg-4 d-lg-flex justify-content-center p-0 border-hide-md" style="min-height: 100px">
		<div class="px-3 py-2 h-100 text-nowrap">
			<a href="https://owen.ru/" target="_blank">
				<img class="align-bottom" src="{% static 'img/logo-owen-white.svg' %}" style="height:30px; padding-right: 6px">
				<img class="align-bottom" src="{% static 'img/slogan-owen-white.svg' %}" style="height:28px;">
			</a>
			<p class="pl-1 mt-2">
				<a class="w3-text-white" href="https://owen.ru/">www.owen.ru</a> <br/>
				E-mail: sales@owen.ru <br>
				1-я ул. Энтузиастов, д. 15, стр. 1
			</p>
		</div>		
	</div>
	<div class="d-lg-none w-100 w3-border-bottom mx-3"></div>

	<div class="col-lg-4 d-lg-flex justify-content-center p-0 w3-border-left w3-border-right border-hide-md" style="min-height: 100px">
		<div class="px-3 py-2 h-100 text-nowrap">
			<h4>Отдел продаж</h4>
			<p>
			Тел.: +7(495) 64-111-56 доб. 2302 <br/>
			Моб.: +7(962) 302-69-16 <br/>
			E-mail: a.bakun@owen.ru
			</p>
		</div>		
	</div>
	<div class="d-lg-none w-100 w3-border-bottom mx-3"></div>

	<div class="col-lg-4 d-lg-flex justify-content-center p-0  border-hide-md" style="min-height: 100px">
		<div class="px-3 py-2 h-100 text-nowrap">
			<h4>Техническая поддержка</h4>
			<p>
			Тел.: +7 (495) 64-111-56 доб. 1901 <br/>
			Моб.: +7 (905) 671-63-24 <br/>
			<!-- Skype: r.gomonilov_owen <br/> -->
			E-mail: a.osipov@owen.ru
			</p>
		</div>
	</div>
	<div class="d-lg-none w-100 w3-border-bottom mx-3"></div>
</div>
</div>
</footer>

owen_agriculture/templates/navbar.html
{% load static %}

<div class="fixed-top w3-white">
<div class="w3-content base-content-width">
	<div class="d-flex">
		<div class="mr-auto p-2">
			<a href="{% url 'home' %}" style="text-decoration: none;">
				<img src="{% static 'img/logo-dark.svg' %}" style="height:38px; padding-top: 2px">
			</a>
		</div>
		<div class="d-none d-md-inline-block text-dark px-2 py-1">
			<p class="p-0 m-0">
				Центральный офис: <b class="text-dark-teal">+7 (495) 64-111-56</b> <br/>
				E-mail: <b><a class="text-dark-teal" href="mailto:sales@owen.ru">sales@owen.ru</a></b>
			</p>
		</div>
	</div>
</div>
</div>

<nav class="fixed-top bg-red" style="margin-top: 55px;">
<div class="d-md-flex justify-content-center">
	<div class="d-md-flex flex-md-row justify-content-center w-100 base-content-width">
		<a class="w3-button w3-large w3-text-light-grey bg-hover-teal w-100 p-1 text-nowrap" style="text-decoration: none; max-width: 100%;" href="{% url 'products:poultry_catalog' %}">Птицеводство</a>
		<a class="w3-button w3-large w3-text-light-grey bg-hover-teal w-100 p-1 text-nowrap" style="text-decoration: none; max-width: 100%;" href="{% url 'products:pigsty_catalog' %}">Свиноводство</a>
		<a class="w3-button w3-large w3-text-light-grey bg-hover-teal w-100 p-1 text-nowrap" style="text-decoration: none; max-width: 100%;" href="{% url 'projects:projects_list' %}">Проекты</a>
		<a class="w3-button w3-large w3-text-light-grey bg-hover-teal w-100 p-1 text-nowrap" style="text-decoration: none; max-width: 100%;" href="{% url 'news:news_list' %}">Новости</a>
		<a class="w3-button w3-large w3-text-light-grey bg-hover-teal w-100 p-1 text-nowrap" style="text-decoration: none; max-width: 100%;" href="{% url 'contacts' %}">Контакты</a>
		<a class="w3-button w3-large w3-text-light-grey bg-hover-teal w-100 p-1 text-nowrap" style="text-decoration: none; max-width: 100%;" href="{% url 'about' %}">О компании</a>
	</div>
</div>
</nav>
<div class="d-md-none" style="height: 203px"></div>
<div class="d-none d-md-inline-block" style="height: 83px"></div>

owen_agriculture/templates/navbar_small_scrin.html
{% load static %}


<nav class="">
	<div class="bg-red navbar navbar-dark p-0">
		<!-- Brand -->
		<a class="navbar-brand my-2 mx-3" href="{% url 'home' %}">
			<img src="{% static 'img/logo-owen-white.svg' %}" style="height:30px;">
		</a>

	    <!-- Toggler/collapsibe Button -->
	    <button class="navbar-toggler my-border-light-grey my-2 mx-3" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
	      <i class="fa fa-navicon" style="color:#fff; font-size:28px;"></i>
	    </button>

	    <!-- Navbar links -->
		<div class="collapse navbar-collapse w3-border-top py-1" id="collapsibleNavbar">
			<div class="d-md-flex justify-content-center w-100 base-content-width">
				<a class="w3-button w3-large w3-text-light-grey bg-hover-teal w-100 p-1 text-nowrap" style="text-decoration: none; max-width: 100%;" href="{% url 'products:poultry_catalog' %}">Птицеводство</a>
				<a class="w3-button w3-large w3-text-light-grey bg-hover-teal w-100 p-1 text-nowrap" style="text-decoration: none; max-width: 100%;" href="{% url 'products:pigsty_catalog' %}">Свиноводство</a>
				<a class="w3-button w3-large w3-text-light-grey bg-hover-teal w-100 p-1 text-nowrap" style="text-decoration: none; max-width: 100%;" href="{% url 'projects:projects_list' %}">Проекты</a>
				<a class="w3-button w3-large w3-text-light-grey bg-hover-teal w-100 p-1 text-nowrap" style="text-decoration: none; max-width: 100%;" href="{% url 'news:news_list' %}">Новости</a>
				<a class="w3-button w3-large w3-text-light-grey bg-hover-teal w-100 p-1 text-nowrap" style="text-decoration: none; max-width: 100%;" href="{% url 'contacts' %}">Контакты</a>
				<a class="w3-button w3-large w3-text-light-grey bg-hover-teal w-100 p-1 text-nowrap" style="text-decoration: none; max-width: 100%;" href="{% url 'about' %}">О компании</a>
			</div>
		</div>
	</div>
</nav>