news/urls.py
from django.urls import path
from news import views

app_name = "news"

urlpatterns = [
	path('', views.news_home, name='news_list'),
    path('<int:id>/', views.news_detail, name='news_detail'),
]

owen_agriculture/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
	path('', views.home, name='home'),
    path('products/', include('products.urls')),
    path('projects/', include('projects.urls')),
    path('news/', include('news.urls')),
    path('contacts/', views.contacts, name='contacts'),
    path('about/', views.about, name='about'),
    path('owen_admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

news/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
import datetime
from PIL import Image

class Article(models.Model):
	header = models.TextField(verbose_name='Название')
	image = models.ImageField(upload_to='news', blank=True, verbose_name='Рисунок')
	short_description = models.TextField(verbose_name='Краткое описание')	 
	text = RichTextUploadingField(verbose_name='Текст')
	pub_date = models.DateField(verbose_name='Дата публикации', default=datetime.date.today)
	display = models.BooleanField(verbose_name='Показывать', default=True)
	
	def __str__ (self):
		return self.header

	class Meta():
		verbose_name = "Новость"
		verbose_name_plural = "Новости"

	def save(self):
		super().save()
		if self.image:
			img = Image.open(self.image.path)
			if img.height > 600 or img.width > 600:
				output_size = (600, 600)
				img.thumbnail(output_size)
				img.save(self.image.path)

news/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404, get_list_or_404
from django.http import Http404
from news.models import Article


def news_home(request):
	try:
		li = Article.objects.filter(display=True).order_by('-pub_date')
	except:
		li = []

	context = {'news_list':li}
	return render(request, 'news/news_home.html', context)


def news_detail(request, id):
	art = get_object_or_404(Article, pk = id)
	context = {'article': art}
	return render(request, 'news/news_detail.html', context)

news/templates/news/news_detail.html
{% extends 'base.html' %}


{% block title %} Owen Agriculture - Новости {% endblock %}

{% block content %} 
	<div class="w3-container w3-card w3-white">
	  <div class="w3-content secondary-content-width">
		<div class="py-4">
			<div class="w3-border-bottom mb-3 mx-0 p-0">
				<h2 class="w3-center p-0 m-0">{{article.header}}</h2>
				<p class="badge badge-light w3-medium header-font w3-white text-teal py-1 px-3 m-0">{{article.pub_date}}</p>
			</div>

			<div class="w3-row">

				{% if article.image %}
				<div class="w3-card w3-col l4 m4 s12 mb-3 p-1">
					<img src="{{article.image.url}}" alt="{{article.header}}" style="width: 100%;">
				</div>
				{% endif %}

				<div class="w3-col l8 m8 s12 w3-medium pl-3">
					<h2 class="w3-medium" style="margin-top: 0"><b>{{article.short_description}}</b></h2>
					{{article.text | safe}}
				</div>
			</div>
		</div>
	  </div> 
	</div>
{% endblock %}

news/templates/news/news_home.html
{% extends 'base.html' %}


{% block title %} Owen Agriculture - Новости {% endblock %}


{% block content %}
	<div class="p-3 w3-card w3-white">
	  <div class="w3-content secondary-content-width">
		<h2>Новости</h2>
		{% include "news/news_list_mini.html" with news_list=news_list only %}
	  </div>
	</div> 
{% endblock %}

news/templates/news/news_list.html
{% if news_list %}
	<div class="conteiner-fluid">
	{% for article in news_list %}
		<div class="conteiner-fluid w3-border-bottom p-0 m-0 mb-3">
		<div class="w3-row">
			{% if article.image %}
				<a href="{% url 'news:news_detail' article.id %}" style="text-decoration: none;" >
					<div class="w3-quarter mr-3 mt-1 mb-3 w3-center" style="width: 250px;">
						<img src="{{article.image.url}}" alt="{{article.header}}"  style="width: 100%;">
					</div>
				</a>
			{% endif %}
			<div class="w3-rest w3-mobile">
				<p class="badge badge-secondary float-right w3-medium p-1 ml-3 my-1">{{article.pub_date}}</p>
				<a href="{% url 'news:news_detail' article.id %}" style="text-decoration: none;" >
					<h3 class="w3-xlarge text-teal text-hover-dark-teal mb-1">{{article.header}}</h3>
				</a>
				<p class="w3-medium">{{article.short_description}}</p>
				<a href="{% url 'news:news_detail' article.id %}" class="w3-button w3-border w3-round bg-hover-teal text-dark-teal py-1 mb-3" style="text-decoration: none;">Подробнее</a>
			</div>
		</div>
		</div>

	{% endfor %}
	</div>

{% else %}
	<br>
	<p class="w3-panel w3-card-2 bg-warning p-2" style="height: 60px;">На текущий момент новости отсутствуют.</p>
{% endif %}

news/templates/news/news_list_mini.html
{% if news_list %}
	<div class="conteiner-fluid article-list">
	{% for article in news_list %}
		<div class="conteiner-fluid w3-border-bottom border-light-grey p-0 m-0 mb-3">
		<div class="w3-row">
			{% if article.image %}
				<a href="{% url 'news:news_detail' article.id %}" style="text-decoration: none;" >
					<div class="w3-col m3 l2 mr-3 mt-1 mb-2 w3-center" >
						<img src="{{article.image.url}}" alt="{{article.header}}"  class="banner-image">
					</div>
				</a>
			{% endif %}
			<div class="w3-rest w3-mobile">
				<p class="badge badge-light float-right w3-small header-font text-teal p-1 ml-2 my-1">{{article.pub_date}}</p>
				<a href="{% url 'news:news_detail' article.id %}" style="text-decoration: none;" >
					<h3 class="w3-large header-font text-teal text-hover-dark-teal mb-1">{{article.header}}</h3>
				</a>
				
				<p class="w3-medium text-font">{{article.short_description}}</p>
				<a href="{% url 'news:news_detail' article.id %}" class="w3-button w3-border w3-round bg-hover-teal text-dark-teal py-1 mb-3" style="text-decoration: none;">Подробнее</a>
			</div>
		</div>
		</div>

	{% endfor %}
	</div>
{% else %}
	<br>
	<p class="w3-panel w3-card-2 bg-warning p-2" style="height: 60px;">На текущий момент новости отсутствуют.</p>
{% endif %}