news/urls.py
from django.urls import path
from news import views

app_name = "news"

urlpatterns = [
	path('', views.news_home, name='news_list'),
    path('<int:id>/', views.news_detail, name='news_detail'),
]

owen_agriculture/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
	path('', views.home, name='home'),
    path('products/', include('products.urls')),
    path('projects/', include('projects.urls')),
    path('news/', include('news.urls')),
    path('contacts/', views.contacts, name='contacts'),
    path('about/', views.about, name='about'),
    path('owen_admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

projects/urls.py
from django.urls import path
from projects import views

app_name = "projects"

urlpatterns = [
	path('', views.projects_list, name='projects_list'),
    path('<int:id>/', views.project_detail, name='project_detail'),
]

projects/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from PIL import Image


class ProjectArticle(models.Model):
	header = models.TextField(verbose_name='Название')
	image = models.ImageField(upload_to='projects', blank=True, verbose_name='Рисунок') 
	short_description = models.TextField(verbose_name='Краткое описание')
	text = RichTextUploadingField(verbose_name='Текст')
	display = models.BooleanField(verbose_name='Показывать', default=True)

	def __str__ (self):
		return self.header

	class Meta():
		verbose_name = "Проект"
		verbose_name_plural = "Проекты"

	def save(self):
		super().save()

		img = Image.open(self.image.path)

		if img.height > 600 or img.width > 600:
			output_size = (600, 600)
			img.thumbnail(output_size)
			img.save(self.image.path)

projects/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404, get_list_or_404
from django.http import Http404
from projects.models import ProjectArticle


def projects_list(request):
	try:
		li = ProjectArticle.objects.filter(display=True).order_by('-id')
	except:
		li = []

	context = {'projects_list':li}
	return render(request, 'projects/projects_home.html', context)


def project_detail(request, id):
	pr = get_object_or_404(ProjectArticle, pk = id)
	context = {'project': pr}
	return render(request, 'projects/project_detail.html', context)

projects/templates/projects/project_detail.html
{% extends 'base.html' %}


{% block title %} Owen Agriculture - Проекты {% endblock %}

{% block content %} 
<div class="w3-white w3-card py-4">
  <div class="w3-content secondary-content-width">	
	<div class="w3-container "> 
		<h2 class="w3-center w3-border-bottom pb-3">{{project.header}}</h2>
		<h2 class="w3-medium pt-2"><b>{{project.short_description}}</b></h2>
		<div>
			{{project.text | safe}}
		</div>
	</div>
	<br>
  </div>
</div>
{% endblock %}

projects/templates/projects/projects_home.html
{% extends 'base.html' %}


{% block title %} Owen Agriculture - Проекты {% endblock %}


{% block content %}
  <div class="p-3 w3-card w3-white base-content-height">
    <div class="w3-content secondary-content-width">
    <h2>Реализованные проекты</h2>

    {% include "projects/projects_list_mini.html" with projects_list=projects_list only %}
    </div>
  </div> 
{% endblock %}

projects/templates/projects/projects_list.html
{% if projects_list %}
	<div class="conteiner-fluid">
	{% for project in projects_list %}
		<div class="conteiner-fluid w3-border-bottom p-0 m-0 mb-3">
		<div class="w3-row">
			{% if project.image %}
				<a href="{% url 'projects:project_detail' project.id %}" style="text-decoration: none;" >
					<div class="w3-quarter mr-3 mt-1 mb-3 w3-center" style="width: 250px;">
						<img src="{{project.image.url}}" alt="{{project.header}}"  style="width: 100%;">
					</div>
				</a>
			{% endif %}
			<div class="w3-rest w3-mobile">
				<p class="badge badge-secondary float-right w3-medium p-1 ml-3 my-1">{{project.pub_date}}</p>
				<a href="{% url 'projects:project_detail' project.id %}" style="text-decoration: none;" >
					<h3 class="w3-xlarge text-teal text-hover-dark-teal mb-1">{{project.header}}</h3>
				</a>
				<p class="w3-medium">{{project.short_description}}</p>
				<a href="{% url 'projects:project_detail' project.id %}" class="w3-button w3-border w3-round bg-hover-teal text-dark-teal py-1 mb-3" style="text-decoration: none;">Подробнее</a>
			</div>
		</div>
		</div>

	{% endfor %}
	</div>

{% else %}
	<br>
	<p class="w3-panel w3-card-2 bg-warning p-2" style="height: 60px;">На текущий момент проекты отсутствуют.</p>
{% endif %}

projects/templates/projects/projects_list_mini.html
{% if projects_list %}
	<div class="conteiner-fluid article-list">
	{% for project in projects_list %}
		<div class="conteiner-fluid w3-border-bottom border-light-grey p-0 m-0 mb-3">
		<div class="w3-row">
			{% if project.image %}
				<a href="{% url 'projects:project_detail' project.id %}" style="text-decoration: none;" >
					<div class="w3-col m3 l2 mr-3 mt-1 mb-2 w3-center">
						<img src="{{project.image.url}}" alt="{{project.header}}" class="banner-image" >
					</div>
				</a>
			{% endif %}
			<div class="w3-rest w3-mobile">
				<a href="{% url 'projects:project_detail' project.id %}" style="text-decoration: none;" >
					<h3 class="w3-large header-font text-teal text-hover-dark-teal mb-1">{{project.header}}</h3>
				</a>
				<p class="w3-medium text-font">{{project.short_description}}</p>
				<a href="{% url 'projects:project_detail' project.id %}" class="w3-button w3-border w3-round bg-hover-teal text-dark-teal py-1 mb-3" style="text-decoration: none;">Подробнее</a>
			</div>
		</div>
		</div>

	{% endfor %}
	</div>
{% else %}
	<br>
	<p class="w3-panel w3-card-2 bg-warning p-2" style="height: 60px;">На текущий момент проекты отсутствуют.</p>
{% endif %}