news/urls.py
from django.urls import path
from news import views

app_name = "news"

urlpatterns = [
	path('', views.news_home, name='news_list'),
    path('<int:id>/', views.news_detail, name='news_detail'),
]

owen_agriculture/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
	path('', views.home, name='home'),
    path('products/', include('products.urls')),
    path('projects/', include('projects.urls')),
    path('news/', include('news.urls')),
    path('contacts/', views.contacts, name='contacts'),
    path('about/', views.about, name='about'),
    path('owen_admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

products/urls.py
from django.urls import path
from products import views

app_name = "products"

urlpatterns = [
	path('poultry/', views.poultry_catalog, name='poultry_catalog'),
    path('pigsty/', views.pigsty_catalog, name='pigsty_catalog'),
    path('catalog/', views.full_catalog, name='full_catalog'),
    path('product/<int:id>', views.product_detail, name='product_detail'),
]

products/models.py
from django.db import models
from django.core.validators import FileExtensionValidator
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
from PIL import Image

class ProductTopic (models.Model):
	headline = models.CharField(verbose_name='Название', max_length=200)
	description = models.TextField(verbose_name='Описание')
	icon_class = models.CharField(default='icon-fan', max_length=100, verbose_name='Символ иконки (CSS-класс)' )
	order = models.PositiveSmallIntegerField(verbose_name='Порядок отображения', default=0)

	def __str__ (self):
		return self.headline

	class Meta():
		verbose_name = "Категория продукта"
		verbose_name_plural = "Категории продуктов"


class Product (models.Model):
	topic = models.ForeignKey(ProductTopic, verbose_name='Категория продукта', on_delete=models.CASCADE)
	name = models.CharField(verbose_name='Полное наименование', max_length=100, blank=False)
	model = models.CharField(verbose_name='Модель', max_length=50, blank=False)
	image = models.ImageField(default='product_default.png', upload_to='products')
	short_description = models.TextField(verbose_name='Краткое описание', default='')
	order = models.PositiveSmallIntegerField(verbose_name='Порядок отображения', default=0)
	used_in_poultry = models.BooleanField(verbose_name='Используется в птицекомплексах', default=False)
	used_in_pigsty = models.BooleanField(verbose_name='Используется в свинокомплексах', default=False)

	def __str__ (self):
		return self.name

	class Meta():
		verbose_name = "Продукт"
		verbose_name_plural = "Продукты"

	def save(self):
		super().save()

		img = Image.open(self.image.path)

		if img.height > 600 or img.width > 600:
			output_size = (600, 600)
			img.thumbnail(output_size)
			img.save(self.image.path)


class ProductSpecificationField(models.Model):
	product = models.ForeignKey(Product, verbose_name='Продукт', on_delete=models.CASCADE)
	header = models.CharField(verbose_name='Оглавление', blank=False, max_length=50)
	specification = RichTextUploadingField (verbose_name='Описание', blank=False)
	order = models.PositiveSmallIntegerField(verbose_name='Порядок отображения', default=0)

	def __str__ (self):
		return 'Описание "%s" для %s' %(self.header, self.product.name)

	class Meta():
		verbose_name = "Раздел описания продукта"
		verbose_name_plural = "Разделы описания продукта"

products/views.py
from django.shortcuts import render
from django.http import Http404
from products.models import ProductTopic, Product, ProductSpecificationField
import sys

# industry names
PIGSTY = 'pigsty'
POULTRY = 'poultry'
FULL = 'full'

def poultry_catalog(request):
	# topic_filter = request.GET.get('topic_filter', '')
	context = _catalog_context_filter(POULTRY)
	return render(request, 'products/catalog.html', context)


def pigsty_catalog(request):
	# topic_filter = request.GET.get('topic_filter', '')	
	context = _catalog_context_filter(PIGSTY)
	return render(request, 'products/catalog.html', context)

def full_catalog(request):
	# topic_filter = request.GET.get('topic_filter', '')
	context = _catalog_context_filter(FULL)
	return render(request, 'products/catalog.html', context)

def _catalog_context_filter(catalog):
	''' 
	Make a page context dictionary filtered by industry
	Returns a context dictionary including a list of topics and a dictionary with them items
	'''

	# get all topics
	all_topics = ProductTopic.objects.order_by('order')

	# get all items in topics with filter by industry
	items = {}
	for topic in all_topics:
		if catalog == PIGSTY:
			items[topic.headline] = topic.product_set.filter(used_in_pigsty = True).order_by('order')
			title = 'Свиноводство'
			cat = 'pigsty'
		elif catalog == POULTRY:
			items[topic.headline] = topic.product_set.filter(used_in_poultry = True).order_by('order')
			title = 'Птицеводство'
			cat = 'poultry'
		elif catalog == FULL:
			items[topic.headline] = topic.product_set.filter()
			title = 'Каталог'
			cat = 'full'		

	# remove all empty topics
	topics = []
	for t in all_topics:
		if items[t.headline] :
			topics.append(t)

	# return just selcted topic items
	# if topic_filter:
	#	sel = topics[topic_filter]
	#	topics = []
	#	topics.append(sel)

	# return page context
	return {'topics': topics, 'items': items, 'title': title, 'catalog':cat }


def product_detail(request, id):
	try:
		product = Product.objects.get(id = id)
	except:
		raise Http404("Продукт не найден")	

	spec = product.productspecificationfield_set.all().order_by('order')
	# print('hello, im here!', spec, file=sys.stderr)
	catalog = request.GET.get('catalog', '')	

	context = {'product': product, 'spec': spec, 'catalog':catalog}
	return render(request, 'products/product_detail.html', context)

products/templates/products/catalog.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap_breadcrumbs %}


{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Главная" "/" %}
	
	{% if catalog == 'pigsty' %}
    	{% breadcrumb "Свиноводство" "products:pigsty_catalog" %}
    {% elif catalog == 'poultry' %}
    	{% breadcrumb "Птицеводство" "products:poultry_catalog" %}
    {% else %}
    	{% breadcrumb "Каталог" "products:full_catalog" %}
    {% endif %}
{% endblock %}


{% block title %} Owen Agriculture - {{title}} {% endblock %}

{% block scrollable %} data-spy="scroll" data-target="#myScrollspy" data-offset="1" {% endblock %}
{% block content %}
	{% if topics %}
	<div class="container-fluid m-0 w3-card " >
	  <div class="row base-content-height">

	    <!-- navbar -->
	    <nav class="col-1 col-lg-3 bg-light-grey p-0" id="myScrollspy" style="min-width:80px; max-width:250px;">
	      <nav class="sidebar mt-0" style="max-width:250px;">
	      	<!-- on larg screen -->
	        <ul class="nav nav-pills flex-column py-2 mx-2 d-none d-lg-inline-block">
	          {% for topic in topics %}
	            <li class="nav-item">
	              <a class="nav-link round-0 w3-border-bottom bg-hover-teal text-teal w3-hover-text-white text-dark-grey w3-medium text-nowrap p-1 mt-1" href="#topic{{forloop.counter}}" style="">
	              	<span class="topic-icon w3-xlarge {{topic.icon_class}} p-1" ></span>
	              	<span class="p-1">{{topic.headline}}</span>
	              </a>
	            </li>
	          {% endfor %}
	        </ul>
	        <!-- on small screen -->
	       	<ul class="nav nav-pills flex-column py-2 mx-2 d-lg-none">
	          {% for topic in topics %}
	            <li class="nav-item">
	              <a class="nav-link round-0 w3-border-bottom bg-hover-teal w3-medium p-1 mt-1 text-center" href="#topic{{forloop.counter}}" style="">
	              	<span class="topic-icon w3-xlarge {{topic.icon_class}} p-1" style="width: 60px"></span>
	              </a>
	            </li>
	          {% endfor %}
	        </ul>
	      </nav>
	    </nav>

		<div class="col ml-1 p-0 w3-white">
		<!-- breadcrumbs -->
		{% render_breadcrumbs %}

		{% for topic in topics %}
			<div id='topic{{forloop.counter}}' class="anchor"></div>
			<div class="container-fluid p-0 px-3 m-0">
				<h1 class="w3-xlarge text-dark py-1 m-0">{{topic.headline}}</h1>
			</div>

			<div class="row pl-3 pr-0 py-2 m-0">
				{% for key, val in items.items %}
					{% if key == topic.headline  %}
						{% if val %}
							{% for item in val %}
								<div class="col-md-3 col-sm-4 mb-3 catalog-card p-0 pr-3">
									<a href="{% url 'products:product_detail' item.id %}?catalog={{catalog}}" style="text-decoration: none;" >

										<div class="container-fluid w3-card m-0 p-0 pt-2 h-100">
											<div class="w3-display-container w3-white my-0 mx-2 p-0" style="height: 180px;">
												<img src="{{item.image.url}}" alt="{{item.name}}" class="w3-display-middle">
											</div>
											<div class="w3-border-top border-grey text-dark mx-3 my-2 px-0 py-2">
												<h5 class="w3-medium catalog-card-header font-weight-bold mb-1">{{item.model}}</h5>
												<p class="w3-medium m-0">{{item.short_description}}</p>
											</div>
										</div>

									</a>
								</div>
							{% endfor %}
						{% else %}
								<div class="col-3">
									<div class="w3-card-2 w3-container w3-margin-bottom w3-pale-red" style="height: 60px;">
										<p>Продукты не найдены</p>
									</div>
								</div>
						{% endif %}
					{% endif %}
				{% endfor %}
				</div>

			{% endfor %}
		</div>
	  </div>
	</div>
	{% else %}
		<br>
		<p class="w3-panel  w3-card-2 bg-warning p-2" style="height: 60px;">На текущий момент в данном каталоге нет продуктов.</p>
		<br>
	{% endif %}
{% endblock %}


{% block sidebar_scripts %}
  <script type="text/javascript" src="{% static 'products/js/sticky_sidebar.js' %}"></script>
{% endblock %}

products/templates/products/product_detail.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap_breadcrumbs %}


{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Главная" "/" %}
	
	{% if catalog == 'pigsty' %}
    	{% breadcrumb "Свиноводство" "products:pigsty_catalog" %}
    {% elif catalog == 'poultry' %}
    	{% breadcrumb "Птицеводство" "products:poultry_catalog" %}
    {% else %}
    	{% breadcrumb "Каталог" "products:full_catalog" %}
    {% endif %}

    {% breadcrumb product.model "products:product_detail" product.id  %}
{% endblock %}

{% block title %} Owen Agriculture - {{product.model}} {% endblock %}

{% block scrollable %} data-spy="scroll" data-target="#myScrollspy" data-offset="1" {% endblock %}
{% block content %}
<div>
<div class="container-fluid m-0 w3-card" >
  <div class="row base-content-height">

    <!-- navbar -->
    <nav class="col-3 d-none d-md-block bg-light-grey" id="myScrollspy" style="min-width:290px; max-width:290px;">
      <nav class="sidebar mt-0" style="width:260px;">
        <a href="#top" style="text-decoration: none;">
          <div class="w3-display-container m-0" style="height: 200px;">
            <img src="{{product.image.url}}" alt="{{product.name}}" class="w3-display-middle py-3" style="max-width: 100%; max-height: 100%">
          </div>
          <h4 class="w3-center w3-large text-dark m-0"><b>{{product.model}}</b></h4>
        </a>

        <ul class="nav nav-pills flex-column py-2">
          {% for s in spec %}
            <li class="nav-item">
              <a class="nav-link round-0 w3-border-bottom bg-hover-teal text-dark-grey w3-medium p-1 mt-1" href="#section{{forloop.counter}}">{{s.header}}</a>
            </li>
          {% endfor %}
        </ul>
      </nav>
    </nav>

    <!-- navbar on small screen -->
    <nav class="col-1 d-md-none p-0" style="min-width:80px; max-width:80px;">
        <!-- open button -->
        <div class="bg-light-grey w3-card w-100 h-100 p-0" id="sidebarSmallPanel">
          <div class="sticky-top" style="z-index: 100">
            <button class="btn btn-light m-2 mt-3" onclick="sidebar_open()">
                <i class="fa fa-list-ul text-teal px-1" style="font-size:32px;"></i>
            </button>
          </div>  
        </div>

        <!-- sidebar content -->
        <div class="sidebar hidden-sidebar" id="sidebarCollapse">
          <div id="myScrollspy">
            <nav class="sidebar m-0">  
              <div class="hidden-sidebar-content bg-light-grey w3-rightbar w3-border-teal px-3" style="width: 300px;">

                <div class="w3-display-container" style="height: 70px">
                  <button class="w3-display-right btn btn-light border my-1" onclick="sidebar_close()">
                    <i class="fa fa-remove text-teal p-1" style="font-size:18px;"></i>
                  </button> 
                  <h4 class="w3-display-left w3-large text-dark pt-3" style="max-width: 70%"><b>{{product.model}}</b></h4>
                </div>

                <ul class="nav nav-pills flex-column ">
                  {% for s in spec %}
                    <li class="nav-item">
                      <a class="nav-link round-0 w3-border-bottom bg-hover-teal text-dark-grey w3-medium p-1 mt-1" href="#section{{forloop.counter}}">{{s.header}}</a>
                    </li>
                  {% endfor %}
                </ul> 

              </div>
            </nav>
          </div>
        </div>
    </nav>

    <!-- product description -->
    <div class="col w3-white ml-1 p-0" style="overflow-x: hidden;">
      <!-- breadcrumbs -->
      {% render_breadcrumbs %}

      <div class="px-3">
        <div id="top" class="anchor" style="top: -130px;"></div>
        <h2 class="w3-border-bottom">{{product.name}}</h2>
        <div class="w3-display-container" style="height: 300px;">
          <img src="{{product.image.url}}" alt="{{product.name}}" class="w3-display-middle" style="max-width: 90%; max-height: 90%">
        </div>
      </div>

      {% for s in spec %}
      <div id="section{{forloop.counter}}" class="anchor"></div>
        <div class="w3-panel bg-grey w3-large p-3">{{s.header}}</div>
        <div class="px-3">
          {{s.specification|safe}}
        </div> 
      {% endfor %}
      
    </div>


  </div>
</div>
</div>

{% endblock %}


{% block sidebar_scripts %}
  <script type="text/javascript" src="{% static 'products/js/sticky_sidebar.js' %}"></script>
  <script type="text/javascript" src="{% static 'products/js/sidebar_collapse.js' %}"></script>
{% endblock %}